os: linux
dist: jammy

language: python
      
before_install:
  - echo "Running on the following travis CI runner"
  - uname -a
  - echo "CMake version on the runner is"
  - cmake --version
  
script:
   - true

  
