os: linux
dist: jammy
compiler: gcc

language: cpp
      
before_install:
  - echo "Running on the following travis CI runner"
  - uname -a
  - echo "CMake version on the runner is"
  - cmake --version

install:
- |
  case "${TRAVIS_OS_NAME:-linux}" in
  linux)
    if [ "$CHECK_REUSE" = "YES" -o "$CHECK_REUSE" = "ONLY" ]; then
      set -e  # because the if below swallows a bad exit status.
      pip3 install reuse
      set +e
    fi
    if [ "$CHECK_REUSE" != "ONLY" -a "$WASM_BUILD" != "YES" ]; then
      ./ci_scripts/install_linux.sh
      echo
      # Get latest cmake so can use Ninja Multi-Config generator.
      echo "Attempting to update cmake"
      echo "cmake is $(which cmake)"
      sudo apt-get upgrade cmake
      echo "After update cmake is $(which cmake)"
      echo "Getting cmake version"
      cmake --version
      echo "Getting /usr/bin/cmake version"
      /usr/bin/cmake --version
    fi
    ;;
  osx)
    ./ci_scripts/install_macos.sh
    ;;
  esac
  
